stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wahyukac0401/httpd:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34841
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
